name: "Bug Report"
description: "Report a reproducible bug / 反馈可复现问题"
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail so maintainers can reproduce quickly.
        感谢反馈，请尽量提供可复现信息，方便快速定位。

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-check / 提交前确认
      options:
        - label: I have searched existing issues and did not find a duplicate. / 我已搜索现有 issue，确认不是重复问题。
          required: true
        - label: I have read README deployment and FAQ sections. / 我已阅读 README 的部署与 FAQ 部分。
          required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Install Method / 部署方式
      options:
        - Docker Compose
        - Docker Run
        - Source (pnpm)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / 版本
      description: "Image tag or commit hash, e.g. `foru17/neko-master:latest` or git SHA"
      placeholder: "foru17/neko-master:latest"
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment / 运行环境
      description: "OS, browser, reverse proxy/tunnel, and key env vars (mask sensitive values)"
      placeholder: |
        - OS: Ubuntu 24.04
        - Browser: Chrome 132
        - Proxy/Tunnel: Nginx / Cloudflare Tunnel / None
        - Env: WEB_EXTERNAL_PORT=3000, WS_EXTERNAL_PORT=3002, COOKIE_SECRET=***
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: Steps to Reproduce / 复现步骤
      placeholder: |
        1. Start service with ...
        2. Open ...
        3. Click ...
        4. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior / 预期行为
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / 实际行为
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots / 日志与截图
      description: "Please paste key logs (docker logs / browser console / network errors)."
      render: shell
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional Context / 补充信息
      description: "Any workaround, frequency, impact scope, etc."
