name: "Support Question"
description: "Ask for help on usage/deployment / 使用与部署求助"
title: "[Support] "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        For faster help, include your deployment method, env, and exact error messages.
        为了更快定位，请提供部署方式、环境和完整报错信息。

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-check / 提交前确认
      options:
        - label: I have read README and FAQ sections. / 我已阅读 README 与 FAQ。
          required: true
        - label: I have searched existing issues for similar questions. / 我已检索过相似问题。
          required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic / 问题类型
      options:
        - Deployment (Docker/Compose)
        - Reverse Proxy / Tunnel
        - Gateway Connection (Clash/Surge)
        - Authentication / Access Control
        - Data / Statistics
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question / 具体问题
      description: "Describe what you are trying to do and where it fails."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment / 运行环境
      placeholder: |
        - Install: Docker Compose
        - OS: Ubuntu 24.04
        - Proxy/Tunnel: Nginx / Cloudflare Tunnel / None
        - Browser: Chrome 132
        - Env: WEB_EXTERNAL_PORT=3000, WS_EXTERNAL_PORT=3002, COOKIE_SECRET=***
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What You Have Tried / 已尝试内容
      description: "Commands run, docs checked, workaround attempts, etc."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / 报错日志
      description: "Paste key outputs from docker logs / browser console / network errors."
      render: shell
    validations:
      required: false
